website: http://ob-mc.net
name: OBGameplayAdjuster
author: Fahrenheit451
version: 1.1
api-version: "1.21"
main: net.obmc.OBGameplayAdjuster.OBGameplayAdjuster
description: Enforces certain gameplay rules - deop on join, force survival mode etc
commands:
  gpa:
    description: OBGameplayAdjuster command.
    usage: Type /gpa for a list of commands